// Verified working Unsplash photo IDs (confirmed in project gallery)
const V: Record<string, string> = {
  fishFarm:    "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=500&q=85",
  fishPond:    "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=500&q=85",
  fishClose:   "https://images.unsplash.com/photo-1560275619-4662e36fa65c?w=500&q=85",
  tilapia:     "https://images.unsplash.com/photo-1524704654690-b56c05c78a00?w=500&q=85",
  colorFish:   "https://images.unsplash.com/photo-1534043464124-3be32fe000c9?w=500&q=85",
  liner:       "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=500&q=85",
  pellets:     "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&q=85",
  waterTest:   "https://images.unsplash.com/photo-1518467166778-b88f373ffec7?w=500&q=85",
  pondWater:   "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&q=85",
  training:    "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=500&q=85",
  greenWater:  "https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=500&q=85",
  nets:        "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=500&q=85",
};

export const COMPANY = {
  name: "Kajjansi Aquaculture Services Centre",
  shortName: "KASC",
  tagline: "Your Premier Partner for Complete Aquaculture Solutions",
  description:
    "Kajjansi Aquaculture Services Centre (KASC) is a premier aquaculture solutions provider based in Kajjansi on Entebbe Road, Uganda. We serve as a comprehensive partner for commercial fish farmers by providing high-quality inputs, advanced farming technology, and technical consultancy services — bridging gaps in the aquaculture value chain through internationally recognised operational standards.",
  phone: "+256 705 641626",
  phone2: "+256 782 520244",
  email: "aquqtechuganda1@gmail.com",
  address: "Kajjansi, Entebbe Road, Uganda",
  farmAddress: "Kajjansi Aquaculture Services Centre, Entebbe Road, Kajjansi, Uganda",
  regions: ["Uganda", "Kenya", "Tanzania", "Rwanda", "South Africa"],
  iso: [
    { code: "ISO 9001:2015", label: "Quality Management Systems" },
    { code: "ISO 14001:2015", label: "Environmental Management Systems" },
    { code: "ISO 45001:2018", label: "Occupational Health & Safety" },
  ],
  social: {
    facebook: "#",
    twitter: "#",
    instagram: "#",
    youtube: "#",
    whatsapp: "+256705641626",
  },
};

export const SERVICES = [
  {
    id: "consultancy",
    slug: "consultancy",
    title: "Aquaculture Consultancy",
    subtitle: "Expert guidance for your fish farming journey",
    icon: "Microscope",
    color: "brand",
    description:
      "Our team of certified aquaculture specialists provides in-depth consultancy services to help you establish, optimise, and scale your fish farming operations across East Africa.",
    features: [
      "Site feasibility studies and assessment",
      "Water quality analysis and testing",
      "Farm design and planning",
      "Species selection and stocking recommendations",
      "Regulatory compliance and licensing support",
      "Business planning and financial projections",
      "On-farm technical support",
    ],
    image: V.fishFarm,
  },
  {
    id: "pond-construction",
    slug: "pond-construction",
    title: "Full Pond Construction",
    subtitle: "Complete pond planning, design, and engineering",
    icon: "Building2",
    color: "green",
    description:
      "We offer complete pond planning, site design, engineering, and construction services for commercial aquaculture projects — from site evaluation and earthwork to aeration system setup.",
    features: [
      "Site evaluation and soil testing",
      "Custom pond design and engineering",
      "Earthwork and excavation",
      "Inlet and outlet structure installation",
      "Aeration system setup",
      "Water supply system integration",
      "Post-construction water quality testing",
    ],
    image: V.fishPond,
  },
  {
    id: "fish-cages",
    slug: "fish-cages",
    title: "Fish Cage Construction & Installation",
    subtitle: "Lake-based aquaculture made professional",
    icon: "Grid3x3",
    color: "brand",
    description:
      "We fabricate and install cage culture systems in lakes and large water bodies, complete with feasibility studies, cage assembly, stocking, and ongoing management support.",
    features: [
      "Lake site feasibility studies",
      "Cage material procurement (HDPE & galvanised)",
      "Custom cage fabrication and assembly",
      "Professional cage installation",
      "Mooring and anchoring systems",
      "Regulatory documentation and licensing",
      "Stocking and management training",
    ],
    image: V.nets,
  },
  {
    id: "dam-liners",
    slug: "dam-liners",
    title: "Dam Liner Supply & Installation",
    subtitle: "Premium UV-resistant HDPE pond liners",
    icon: "Layers",
    color: "green",
    description:
      "We supply, fabricate, and install high-quality HDPE geomembrane dam liners suitable for fish ponds, irrigation reservoirs, water storage tanks, and PVC mesh tanks.",
    features: [
      "0.5mm, 0.75mm, and 1.0mm thickness options",
      "100% UV-treated for multi-year outdoor use",
      "Machine-welded seams for watertight integrity",
      "Pneumatic leak testing at all seam points",
      "Custom fabrication to any shape or size",
      "Applications: fish ponds, irrigation, water storage",
      "After-sales service and warranty support",
    ],
    image: V.liner,
  },
  {
    id: "training",
    slug: "training",
    title: "Aquaculture Training",
    subtitle: "Build skills that translate to real farm success",
    icon: "GraduationCap",
    color: "amber",
    description:
      "Our hands-on training programmes at the Kajjansi demonstration farm cover all aspects of commercial fish farming — from basic husbandry to advanced cage culture and liner installation.",
    features: [
      "Fish farming fundamentals for beginners",
      "Advanced aquaculture management",
      "Dam liner installation certification",
      "Water quality monitoring and management",
      "Fish health and disease management",
      "Business management for fish farmers",
      "On-farm practical demonstrations",
    ],
    image: V.training,
  },
];

export const PRODUCTS = [
  // ── FINGERLINGS ──────────────────────────────────────────────────────────
  {
    id: "nile-tilapia-fingerlings",
    slug: "nile-tilapia-fingerlings",
    name: "Nile Tilapia Fingerlings",
    category: "fingerlings",
    price: 500,
    unit: "per fingerling",
    description:
      "Premium quality Nile Tilapia fingerlings (Oreochromis niloticus) bred at our certified hatchery. Fast-growing, disease-resistant, and certified for commercial stocking.",
    specs: ["4–6 cm average size", "Certified disease-free", "Minimum order: 500", "Delivery available"],
    image: V.tilapia,
    badge: "Best Seller",
    inStock: true,
    caption: "Healthy Nile Tilapia fingerlings bred at our on-site certified hatchery for maximum survival rates and fast growth.",
  },
  {
    id: "african-catfish-fingerlings",
    slug: "african-catfish-fingerlings",
    name: "African Catfish Fingerlings",
    category: "fingerlings",
    price: 600,
    unit: "per fingerling",
    description:
      "Hardy and fast-growing African Catfish (Clarias gariepinus) fingerlings — ideal for pond and tank culture in East Africa's climate. High survival rate and excellent feed conversion.",
    specs: ["5–7 cm average size", "High survival rate", "Minimum order: 300", "Nationwide delivery"],
    image: V.fishFarm,
    inStock: true,
    caption: "Hardy African Catfish fingerlings known for rapid growth and resilience in all pond conditions.",
  },
  {
    id: "miracle-tilapia-fingerlings",
    slug: "miracle-tilapia-fingerlings",
    name: "Miracle Tilapia Fingerlings",
    category: "fingerlings",
    price: 700,
    unit: "per fingerling",
    description:
      "High-performance Miracle Tilapia fingerlings with exceptional growth rates and tolerance to a wide range of water conditions — ideal for intensive production systems.",
    specs: ["Superior growth genetics", "Disease resistant", "Minimum order: 500", "Delivery available"],
    image: V.fishClose,
    badge: "Premium",
    inStock: true,
    caption: "Genetically superior Miracle Tilapia fingerlings for intensive, high-yield production systems.",
  },

  // ── FISH FEED ──────────────────────────────────────────────────────────
  {
    id: "fish-feed-starter",
    slug: "fish-feed-starter",
    name: "Fish Starter Feed — Powder (0–1mm)",
    category: "feed",
    price: 85000,
    unit: "per 25 kg bag",
    description:
      "Highly digestible powder feed for fry and juvenile fish. Formulated for optimal growth in the critical early stages with 45% protein content. Promotes uniform growth and reduces early-stage mortality.",
    specs: ["45% crude protein", "Powder / 1 mm crumble", "25 kg packaging", "For fry & fingerlings"],
    image: V.pellets,
    badge: "New",
    inStock: true,
    caption: "High-protein powder starter feed for fry — ensures rapid early growth and uniform fingerling size.",
  },
  {
    id: "fish-feed-grower",
    slug: "fish-feed-grower",
    name: "Fish Grower Pellets (3mm)",
    category: "feed",
    price: 75000,
    unit: "per 25 kg bag",
    description:
      "Balanced floating pellets for growing and sub-adult fish. Supports rapid weight gain, excellent feed conversion, and vibrant colouration. Available in both sinking and floating options.",
    specs: ["38% crude protein", "3 mm pellet", "25 kg packaging", "Floating & sinking options"],
    image: V.pellets,
    inStock: true,
    caption: "Nutritionally balanced 3 mm pellets formulated for fast weight gain and optimum feed conversion.",
  },
  {
    id: "fish-feed-finisher",
    slug: "fish-feed-finisher",
    name: "Fish Finisher Pellets (5mm)",
    category: "feed",
    price: 70000,
    unit: "per 25 kg bag",
    description:
      "Large 5 mm pellets for market-size fish in the final grow-out stage. High energy formulation maximises weight gain in the last 4–6 weeks before harvest.",
    specs: ["35% crude protein", "5 mm pellet", "25 kg packaging", "Sinking pellets"],
    image: V.pellets,
    inStock: true,
    caption: "High-energy 5 mm finisher pellets to push fish to market weight quickly in the last grow-out weeks.",
  },
  {
    id: "azolla",
    slug: "azolla",
    name: "Azolla (Aquatic Fern Supplement)",
    category: "feed",
    price: 15000,
    unit: "per kg (fresh)",
    description:
      "Fresh Azolla pinnata — a nitrogen-fixing aquatic fern used as a natural protein-rich supplement in fish and poultry feed. High in protein (25–30%), vitamins, and minerals. Reduces feed costs significantly.",
    specs: ["25–30% crude protein", "Rich in vitamins A & B12", "Nitrogen-fixing plant", "Fresh or dried supply"],
    image: V.greenWater,
    inStock: true,
    caption: "Fresh Azolla — a natural protein-rich aquatic fern supplement that cuts feed costs and boosts nutrition.",
  },

  // ── DAM LINERS ──────────────────────────────────────────────────────────
  {
    id: "dam-liner-05mm",
    slug: "dam-liner-05mm",
    name: "HDPE Geomembrane Liner 0.5mm",
    category: "liners",
    price: 12000,
    unit: "per m²",
    description:
      "UV-treated 0.5mm HDPE geomembrane liner — ideal for small fish ponds, backyard water storage, and low-pressure irrigation reservoirs. Fully leak-proof and durable.",
    specs: ["0.5mm thickness", "UV treated", "Black HDPE", "Custom sizes available"],
    image: V.liner,
    inStock: true,
    caption: "0.5 mm HDPE liner for small ponds and irrigation tanks. Fully leak-proof with UV protection.",
  },
  {
    id: "dam-liner-075mm",
    slug: "dam-liner-075mm",
    name: "HDPE Geomembrane Liner 0.75mm",
    category: "liners",
    price: 16000,
    unit: "per m²",
    description:
      "Medium-duty 0.75mm UV-treated HDPE liner — the most popular choice for commercial fish ponds, irrigation canals, and farm water reservoirs. Machine-welded seams for watertight integrity.",
    specs: ["0.75mm thickness", "UV treated", "Black HDPE", "Machine-welded seams"],
    image: V.liner,
    badge: "Most Popular",
    inStock: true,
    caption: "The most trusted liner for commercial ponds — 0.75 mm HDPE with machine-welded watertight seams.",
  },
  {
    id: "dam-liner-1mm",
    slug: "dam-liner-1mm",
    name: "HDPE Geomembrane Liner 1.0mm",
    category: "liners",
    price: 22000,
    unit: "per m²",
    description:
      "Heavy-duty 1.0mm liner for large-scale commercial fish farms, industrial water storage, and high-pressure applications. 15+ year lifespan with puncture resistance.",
    specs: ["1.0mm thickness", "UV treated", "High puncture resistance", "15+ year lifespan"],
    image: V.liner,
    badge: "Heavy Duty",
    inStock: true,
    caption: "Heavy-duty 1.0 mm HDPE for large commercial farms and high-pressure storage — 15+ year lifespan.",
  },

  // ── NETS ──────────────────────────────────────────────────────────────
  {
    id: "seine-net",
    slug: "seine-net",
    name: "Pond Seine Net",
    category: "nets",
    price: 180000,
    unit: "per unit",
    description:
      "Heavy-duty knotless nylon seine net for complete pond harvesting. Available in multiple mesh sizes to match your target species. Includes floats and sinkers.",
    specs: ["Knotless nylon mesh", "Multiple mesh sizes", "Floats & sinkers included", "Custom length available"],
    image: V.nets,
    badge: "Best Seller",
    inStock: true,
    caption: "Professional-grade seine net for efficient full-pond harvesting — comes with floats and sinkers.",
  },
  {
    id: "predator-net",
    slug: "predator-net",
    name: "Predator Exclusion Net",
    category: "nets",
    price: 120000,
    unit: "per unit",
    description:
      "UV-stabilised predator exclusion net to protect fish from birds, monitor lizards, and other predators. Easy to install over any pond shape.",
    specs: ["UV-stabilised nylon", "Fine bird-proof mesh", "Includes pegs & rope", "Custom sizes available"],
    image: V.nets,
    inStock: true,
    caption: "Protect your fish from birds and monitor lizards with this UV-stabilised predator exclusion net.",
  },
  {
    id: "hapa-net",
    slug: "hapa-net",
    name: "Hapa Net (Breeding / Nursery)",
    category: "nets",
    price: 95000,
    unit: "per unit",
    description:
      "Fine-mesh hapa net for breeding, nursery management, and fingerling holding within larger ponds. Keeps fry separated for controlled feeding and monitoring.",
    specs: ["Fine nylon mesh", "Reinforced frame pocket", "Various sizes", "Easy to anchor"],
    image: V.nets,
    inStock: true,
    caption: "Fine-mesh hapa nets for nursery management — keep fry in controlled sub-enclosures within larger ponds.",
  },
  {
    id: "fry-net",
    slug: "fry-net",
    name: "Fry Collection Net",
    category: "nets",
    price: 45000,
    unit: "per unit",
    description:
      "Ultra-fine mesh fry collection net for safely transferring newly hatched fry without stress or injury. Soft mesh minimises fin damage during handling.",
    specs: ["Ultra-fine soft mesh", "Padded rim", "Multiple sizes", "Lightweight frame"],
    image: V.nets,
    inStock: true,
    caption: "Ultra-fine soft-mesh net for gentle fry collection — minimises stress and fin damage during transfer.",
  },
  {
    id: "cage-net",
    slug: "cage-net",
    name: "Cage Culture Net",
    category: "nets",
    price: 350000,
    unit: "per unit",
    description:
      "Heavy-duty HDPE cage net for lake and dam cage aquaculture. Corrosion-resistant, UV-stabilised, and designed to maintain shape under water current.",
    specs: ["HDPE knotless mesh", "UV-stabilised", "Corrosion-resistant", "Custom cage sizes"],
    image: V.nets,
    inStock: true,
    caption: "Heavy-duty HDPE cage nets for lake-based aquaculture — UV-stable and corrosion-resistant.",
  },
  {
    id: "scoop-net",
    slug: "scoop-net",
    name: "Adjustable Scoop Net",
    category: "nets",
    price: 55000,
    unit: "per unit",
    description:
      "Professional adjustable scoop net with telescoping handle for easy pond-side fish handling. Bar spacing fully adjustable to select fish by size without unnecessary stress.",
    specs: ["Adjustable bar spacing", "Telescoping handle", "Stainless steel frame", "Knotless soft mesh"],
    image: V.nets,
    inStock: true,
    caption: "Adjustable scoop net with telescoping handle — select fish by size without stressing your stock.",
  },

  // ── WATER QUALITY EQUIPMENT ──────────────────────────────────────────────
  {
    id: "do-meter",
    slug: "do-meter",
    name: "Dissolved Oxygen (DO) Meter",
    category: "equipment",
    price: 380000,
    unit: "per unit",
    description:
      "Professional digital dissolved oxygen meter for real-time pond monitoring. Essential for preventing fish kills caused by oxygen depletion. Waterproof, field-portable design.",
    specs: ["0–20 mg/L range", "±0.1 mg/L accuracy", "Waterproof IP67", "Auto-calibration"],
    image: V.waterTest,
    badge: "Essential",
    inStock: true,
    caption: "Digital DO meter for real-time oxygen monitoring — prevent fish kills before they happen.",
  },
  {
    id: "ammonia-test-kit",
    slug: "ammonia-test-kit",
    name: "Ammonia Test Kit",
    category: "equipment",
    price: 85000,
    unit: "per kit",
    description:
      "Colorimetric ammonia test kit for monitoring total ammonia nitrogen (TAN) and free ammonia (NH₃) in fish ponds. Early detection prevents toxic build-up and fish stress.",
    specs: ["50 tests per kit", "Detects 0–8 mg/L NH₃-N", "Includes colour chart", "No equipment needed"],
    image: V.waterTest,
    inStock: true,
    caption: "Colorimetric ammonia kit — detects toxic ammonia build-up before it harms your fish.",
  },
  {
    id: "nitrate-test-kit",
    slug: "nitrate-test-kit",
    name: "Nitrate Test Kit",
    category: "equipment",
    price: 75000,
    unit: "per kit",
    description:
      "Reliable nitrate test kit for monitoring NO₃ levels in fish ponds. High nitrate indicates pond overloading — early detection enables corrective water changes.",
    specs: ["50 tests per kit", "Detects 0–50 mg/L NO₃", "Includes colour chart", "Easy liquid reagent"],
    image: V.waterTest,
    inStock: true,
    caption: "Nitrate test kit to monitor pond loading — high NO₃ signals when to do a corrective water change.",
  },
  {
    id: "water-testing-kit",
    slug: "water-testing-kit",
    name: "Multi-Parameter Water Test Kit",
    category: "equipment",
    price: 450000,
    unit: "per kit",
    description:
      "Professional-grade field water testing kit for real-time monitoring of pH, dissolved oxygen, ammonia, nitrite, temperature, and turbidity — everything in one portable case.",
    specs: ["Tests 6 parameters", "100 test capacity", "Field-portable case", "Includes reference chart"],
    image: V.waterTest,
    inStock: true,
    caption: "Complete 6-parameter water quality kit — pH, DO, ammonia, nitrite, temperature, and turbidity.",
  },

  // ── OTHER EQUIPMENT ──────────────────────────────────────────────────
  {
    id: "aerator",
    slug: "aerator",
    name: "Paddle Wheel Aerator (1HP)",
    category: "equipment",
    price: 1200000,
    unit: "per unit",
    description:
      "1 HP paddle wheel aerator for intensive pond oxygenation. Increases dissolved oxygen, reduces ammonia build-up, and improves fish health and growth rates significantly.",
    specs: ["1 HP motor", "240V / solar-compatible", "Stainless steel paddles", "Floats included"],
    image: V.pondWater,
    inStock: true,
    caption: "1 HP paddle wheel aerator — keeps DO levels optimal and reduces ammonia in high-density ponds.",
  },
  {
    id: "chest-waders",
    slug: "chest-waders",
    name: "PVC Chest Waders",
    category: "equipment",
    price: 180000,
    unit: "per pair",
    description:
      "Heavy-duty waterproof PVC chest waders for safe pond entry during feeding, harvesting, and maintenance. Slip-resistant sole and adjustable suspenders.",
    specs: ["PVC waterproof material", "Slip-resistant sole", "Adjustable suspenders", "Sizes: S, M, L, XL"],
    image: V.training,
    inStock: true,
    caption: "Waterproof PVC chest waders for safe pond entry — essential for feeding, harvesting, and maintenance.",
  },
  {
    id: "aquarium",
    slug: "aquarium",
    name: "Glass Aquarium (Hatchery Display)",
    category: "equipment",
    price: 250000,
    unit: "per unit",
    description:
      "Clear glass aquarium for hatchery observation, fingerling holding, and breeding pair monitoring. Tempered glass with silicone seals, lid, and aeration port.",
    specs: ["100L capacity", "Tempered glass", "Includes lid & filter port", "Acrylic legs"],
    image: V.colorFish,
    inStock: true,
    caption: "Glass hatchery aquarium for fingerling observation, breeding monitoring, and stock display.",
  },
  {
    id: "fish-grader",
    slug: "fish-grader",
    name: "Adjustable Fish Grader",
    category: "equipment",
    price: 280000,
    unit: "per unit",
    description:
      "Durable adjustable bar grader for sorting fish by size. Reduces stress during grading and ensures uniform stocking density for better growth performance.",
    specs: ["Adjustable bar spacing", "Stainless steel", "Handles up to 500g fish", "Easy to clean"],
    image: V.fishFarm,
    inStock: true,
    caption: "Stainless steel adjustable grader — sort fish by size for uniform stocking and optimised growth.",
  },
  {
    id: "secchi-disk",
    slug: "secchi-disk",
    name: "Secchi Disk",
    category: "equipment",
    price: 45000,
    unit: "per unit",
    description:
      "Standard 20 cm Secchi disk for measuring water transparency and phytoplankton density — essential for daily pond water quality management.",
    specs: ["20 cm diameter", "Stainless steel", "10 m rope included", "Graduated markings"],
    image: V.waterTest,
    inStock: true,
    caption: "Secchi disk for pond transparency — guides daily water quality decisions and optimal feeding rates.",
  },
];

export const STATS = [
  { value: "500+", label: "Fish Farmers Served", icon: "Users" },
  { value: "10+", label: "Years of Experience", icon: "Award" },
  { value: "5", label: "Countries Covered", icon: "Globe" },
  { value: "1M+", label: "Fingerlings Supplied", icon: "Fish" },
];

export const TESTIMONIALS = [
  {
    name: "John Mugisha",
    role: "Fish Farmer, Masaka",
    content:
      "KASC transformed my small pond into a profitable commercial farm. Their consultancy and quality fingerlings gave me a harvest I never expected in my first year.",
    rating: 5,
    avatar: "JM",
  },
  {
    name: "Sarah Akinyi",
    role: "Aquaculture Entrepreneur, Kisumu",
    content:
      "The dam liner installation team was professional, fast, and thorough. They stayed two extra days to ensure everything was perfect. Exceptional after-sales service.",
    rating: 5,
    avatar: "SA",
  },
  {
    name: "Robert Ssemwogerere",
    role: "Farm Manager, Wakiso",
    content:
      "We attended their training programme and came away with practical knowledge we applied immediately. The hands-on sessions at the Kajjansi farm were invaluable.",
    rating: 5,
    avatar: "RS",
  },
  {
    name: "Grace Mwangi",
    role: "Fish Farmer, Nakuru, Kenya",
    content:
      "The fish feed quality is outstanding. My tilapia reached market weight two weeks earlier than with my previous supplier's feed. Will never switch.",
    rating: 5,
    avatar: "GM",
  },
];

export const NAV_ITEMS = [
  { label: "Home", href: "/" },
  {
    label: "Services",
    href: "/services",
    children: [
      { label: "Aquaculture Consultancy", href: "/services/consultancy" },
      { label: "Fish Pond Construction", href: "/services/pond-construction" },
      { label: "Fish Cage Installation", href: "/services/fish-cages" },
      { label: "Dam Liner Supply & Installation", href: "/services/dam-liners" },
      { label: "Training Programmes", href: "/services/training" },
    ],
  },
  { label: "Shop", href: "/shop" },
  { label: "Our Farm", href: "/farm" },
  { label: "Gallery", href: "/gallery" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];
