export const COMPANY = {
  name: "Kajjansi Aquaculture Service Center",
  shortName: "KASC",
  tagline: "Your One-Stop Aquaculture Solutions Partner",
  description:
    "Kajjansi Aquaculture Service Center is East Africa's leading one-stop center for innovative aquaculture solutions — empowering fish farmers through consultancy, infrastructure, quality inputs, and ongoing support.",
  phone: "+256 700 000000",
  email: "info@kajansiaquaculture.com",
  address: "Kajjansi, Wakiso District, Uganda",
  farmAddress: "Kajjansi Fish Farm, Off Entebbe Road, Wakiso, Uganda",
  regions: ["Uganda", "Kenya", "Tanzania", "Rwanda", "South Africa"],
  social: {
    facebook: "#",
    twitter: "#",
    instagram: "#",
    youtube: "#",
    whatsapp: "+256700000000",
  },
};

export const SERVICES = [
  {
    id: "consultancy",
    slug: "consultancy",
    title: "Aquaculture Consultancy",
    subtitle: "Expert guidance for your fish farming journey",
    icon: "Microscope",
    color: "brand",
    description:
      "Our team of certified aquaculture specialists provides in-depth consultancy services to help you establish, optimize, and scale your fish farming operations across East Africa.",
    features: [
      "Site feasibility studies and assessment",
      "Water quality analysis and testing",
      "Farm design and planning",
      "Species selection and stocking recommendations",
      "Regulatory compliance and licensing support",
      "Business planning and financial projections",
      "On-farm technical support",
    ],
    image: "/images/services/consultancy.jpg",
  },
  {
    id: "pond-construction",
    slug: "pond-construction",
    title: "Fish Pond Construction",
    subtitle: "Building foundations for profitable fish farming",
    icon: "Building2",
    color: "green",
    description:
      "We design and construct high-quality fish ponds tailored to your specific needs, soil type, water source, and target species — ensuring maximum productivity and longevity.",
    features: [
      "Site evaluation and soil testing",
      "Custom pond design and engineering",
      "Earthwork and excavation",
      "Inlet and outlet structure installation",
      "Aeration system setup",
      "Water supply system integration",
      "Post-construction water quality testing",
    ],
    image: "/images/services/pond-construction.jpg",
  },
  {
    id: "fish-cages",
    slug: "fish-cages",
    title: "Fish Cage Construction & Installation",
    subtitle: "Lake-based aquaculture made professional",
    icon: "Grid3x3",
    color: "brand",
    description:
      "We fabricate and install cage culture systems in lakes and large water bodies, complete with feasibility studies, cage assembly, stocking, and ongoing management support.",
    features: [
      "Lake site feasibility studies",
      "Cage material procurement (HDPE & galvanized)",
      "Custom cage fabrication and assembly",
      "Professional cage installation",
      "Mooring and anchoring systems",
      "Regulatory documentation and licensing",
      "Stocking and management training",
    ],
    image: "/images/services/fish-cages.jpg",
  },
  {
    id: "dam-liners",
    slug: "dam-liners",
    title: "Dam Liner Supply & Installation",
    subtitle: "Premium UV-resistant pond liners for lasting results",
    icon: "Layers",
    color: "green",
    description:
      "We supply, fabricate, and install high-quality HDPE geomembrane dam liners suitable for fish ponds, irrigation reservoirs, water storage tanks, and PVC mesh tanks.",
    features: [
      "0.5mm, 0.75mm, and 1.0mm thickness options",
      "100% UV-treated for multi-year outdoor use",
      "Machine-welded seams for watertight integrity",
      "Pneumatic leak testing at all seam points",
      "Custom fabrication to any shape or size",
      "Applications: fish ponds, irrigation, water storage",
      "After-sales service and warranty support",
      "Dam liner installation training programs",
    ],
    image: "/images/services/dam-liners.jpg",
  },
  {
    id: "training",
    slug: "training",
    title: "Aquaculture Training",
    subtitle: "Build skills that translate to real farm success",
    icon: "GraduationCap",
    color: "amber",
    description:
      "Our hands-on training programs at the Kajjansi demonstration farm cover all aspects of commercial fish farming — from basic husbandry to advanced cage culture and liner installation.",
    features: [
      "Fish farming fundamentals for beginners",
      "Advanced aquaculture management",
      "Dam liner installation certification",
      "Water quality monitoring and management",
      "Fish health and disease management",
      "Business management for fish farmers",
      "On-farm practical demonstrations",
    ],
    image: "/images/services/training.jpg",
  },
];

export const PRODUCTS = [
  {
    id: "nile-tilapia-fingerlings",
    slug: "nile-tilapia-fingerlings",
    name: "Nile Tilapia Fingerlings",
    category: "fingerlings",
    price: 500,
    unit: "per fingerling",
    description:
      "Premium quality Nile Tilapia fingerlings (Oreochromis niloticus) bred at our certified hatchery. Fast-growing, disease-resistant, and certified for commercial stocking.",
    specs: ["4–6 cm average size", "Certified disease-free", "Minimum order: 500 fingerlings", "Delivery available"],
    image: "/images/products/tilapia-fingerlings.jpg",
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "african-catfish-fingerlings",
    slug: "african-catfish-fingerlings",
    name: "African Catfish Fingerlings",
    category: "fingerlings",
    price: 600,
    unit: "per fingerling",
    description:
      "Hardy and fast-growing African Catfish (Clarias gariepinus) fingerlings, ideal for pond and tank culture systems in East Africa's climate.",
    specs: ["5–7 cm average size", "High survival rate", "Minimum order: 300 fingerlings", "Nationwide delivery"],
    image: "/images/products/catfish-fingerlings.jpg",
    inStock: true,
  },
  {
    id: "miracle-tilapia-fingerlings",
    slug: "miracle-tilapia-fingerlings",
    name: "Miracle Tilapia Fingerlings",
    category: "fingerlings",
    price: 700,
    unit: "per fingerling",
    description:
      "High-performance Miracle Tilapia fingerlings known for exceptional growth rates and tolerance to a wide range of water conditions.",
    specs: ["Superior growth genetics", "Disease resistant", "Minimum order: 500 fingerlings", "Delivery available"],
    image: "/images/products/miracle-tilapia.jpg",
    badge: "Premium",
    inStock: true,
  },
  {
    id: "fish-feed-starter",
    slug: "fish-feed-starter",
    name: "Fish Starter Feed (1mm)",
    category: "feed",
    price: 85000,
    unit: "per 25kg bag",
    description:
      "Highly digestible starter pellets for fry and juvenile fish. Formulated for optimal growth in the critical early stages with 45% protein content.",
    specs: ["45% crude protein", "1mm pellet size", "25kg packaging", "Floating pellets"],
    image: "/images/products/fish-feed-starter.jpg",
    badge: "New",
    inStock: true,
  },
  {
    id: "fish-feed-grower",
    slug: "fish-feed-grower",
    name: "Fish Grower Feed (3mm)",
    category: "feed",
    price: 75000,
    unit: "per 25kg bag",
    description:
      "Balanced grower pellets for sub-adult and growing fish. Supports rapid weight gain and excellent feed conversion ratio.",
    specs: ["38% crude protein", "3mm pellet size", "25kg packaging", "Sinking/floating options"],
    image: "/images/products/fish-feed-grower.jpg",
    inStock: true,
  },
  {
    id: "dam-liner-05mm",
    slug: "dam-liner-05mm",
    name: "HDPE Dam Liner 0.5mm",
    category: "liners",
    price: 12000,
    unit: "per m²",
    description:
      "UV-treated 0.5mm HDPE geomembrane liner. Ideal for small fish ponds, backyard water storage, and low-pressure irrigation reservoirs.",
    specs: ["0.5mm thickness", "UV treated", "Black HDPE", "Custom sizes available"],
    image: "/images/products/dam-liner-05.jpg",
    inStock: true,
  },
  {
    id: "dam-liner-075mm",
    slug: "dam-liner-075mm",
    name: "HDPE Dam Liner 0.75mm",
    category: "liners",
    price: 16000,
    unit: "per m²",
    description:
      "Medium-duty 0.75mm UV-treated HDPE liner — the most popular choice for commercial fish ponds, irrigation canals, and farm water reservoirs.",
    specs: ["0.75mm thickness", "UV treated", "Black HDPE", "Machine-welded seams"],
    image: "/images/products/dam-liner-075.jpg",
    badge: "Most Popular",
    inStock: true,
  },
  {
    id: "dam-liner-1mm",
    slug: "dam-liner-1mm",
    name: "HDPE Dam Liner 1.0mm",
    category: "liners",
    price: 22000,
    unit: "per m²",
    description:
      "Heavy-duty 1.0mm liner for large-scale commercial fish farms, industrial water storage, and high-pressure applications.",
    specs: ["1.0mm thickness", "UV treated", "High puncture resistance", "15+ year lifespan"],
    image: "/images/products/dam-liner-1.jpg",
    badge: "Heavy Duty",
    inStock: true,
  },
  {
    id: "water-testing-kit",
    slug: "water-testing-kit",
    name: "Multi-Parameter Water Test Kit",
    category: "equipment",
    price: 450000,
    unit: "per kit",
    description:
      "Professional-grade field water testing kit for real-time monitoring of pH, dissolved oxygen, ammonia, nitrite, temperature, and turbidity.",
    specs: ["Tests 6 parameters", "100 test capacity", "Field-portable", "Includes reference chart"],
    image: "/images/products/water-test-kit.jpg",
    inStock: true,
  },
  {
    id: "fish-grader",
    slug: "fish-grader",
    name: "Adjustable Fish Grader",
    category: "equipment",
    price: 280000,
    unit: "per unit",
    description:
      "Durable adjustable grader for sorting fish by size. Reduces stress during grading and ensures uniform stocking density for better growth.",
    specs: ["Adjustable bar spacing", "Stainless steel", "Handles up to 500g fish", "Easy to clean"],
    image: "/images/products/fish-grader.jpg",
    inStock: true,
  },
  {
    id: "secchi-disk",
    slug: "secchi-disk",
    name: "Secchi Disk",
    category: "equipment",
    price: 45000,
    unit: "per unit",
    description:
      "Standard 20cm Secchi disk for measuring water transparency and phytoplankton density — essential for pond water quality management.",
    specs: ["20cm diameter", "Stainless steel", "10m rope included", "Graduated rope markings"],
    image: "/images/products/secchi-disk.jpg",
    inStock: true,
  },
  {
    id: "pond-net",
    slug: "pond-net",
    name: "Pond Seine Net",
    category: "equipment",
    price: 180000,
    unit: "per unit",
    description:
      "Heavy-duty seine net for pond harvesting. Available in multiple mesh sizes to match your target species and size class.",
    specs: ["Nylon knotless mesh", "Multiple mesh sizes", "Floats and sinkers included", "Custom length available"],
    image: "/images/products/seine-net.jpg",
    inStock: true,
  },
];

export const STATS = [
  { value: "500+", label: "Fish Farmers Served", icon: "Users" },
  { value: "10+", label: "Years of Experience", icon: "Award" },
  { value: "5", label: "Countries Covered", icon: "Globe" },
  { value: "1M+", label: "Fingerlings Supplied", icon: "Fish" },
];

export const TESTIMONIALS = [
  {
    name: "John Mugisha",
    role: "Fish Farmer, Masaka",
    content:
      "KASC transformed my small pond into a profitable commercial farm. Their consultancy and quality fingerlings gave me a harvest I never expected in my first year.",
    rating: 5,
    avatar: "JM",
  },
  {
    name: "Sarah Akinyi",
    role: "Aquaculture Entrepreneur, Kisumu, Kenya",
    content:
      "The dam liner installation team was professional, fast, and thorough. They even stayed for two days after to ensure everything was perfect. Exceptional after-sales service.",
    rating: 5,
    avatar: "SA",
  },
  {
    name: "Robert Ssemwogerere",
    role: "Farm Manager, Wakiso",
    content:
      "We attended their training program and came away with practical knowledge that we applied immediately. The hands-on sessions at the Kajjansi farm were invaluable.",
    rating: 5,
    avatar: "RS",
  },
  {
    name: "Grace Mwangi",
    role: "Fish Farmer, Nakuru, Kenya",
    content:
      "The fish feed quality is outstanding. My tilapia reached market weight two weeks earlier than my previous supplier's feed. Will never switch.",
    rating: 5,
    avatar: "GM",
  },
];

export const NAV_ITEMS = [
  { label: "Home", href: "/" },
  {
    label: "Services",
    href: "/services",
    children: [
      { label: "Aquaculture Consultancy", href: "/services/consultancy" },
      { label: "Fish Pond Construction", href: "/services/pond-construction" },
      { label: "Fish Cage Installation", href: "/services/fish-cages" },
      { label: "Dam Liner Supply & Installation", href: "/services/dam-liners" },
      { label: "Training Programs", href: "/services/training" },
    ],
  },
  { label: "Shop", href: "/shop" },
  { label: "Our Farm", href: "/farm" },
  { label: "Gallery", href: "/gallery" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];
